# Generated by Django 3.0.5 on 2020-04-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innapp', '0002_all_bloodimg_foodimg_moneyimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jointsecretory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='jointsecretory')),
                ('phone', models.IntegerField()),
                ('Address', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
