# Generated by Django 2.2.6 on 2020-03-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodonate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=50)),
                ('mblno', models.IntegerField()),
                ('maddress', models.CharField(max_length=300)),
                ('memail', models.EmailField(max_length=254)),
                ('mimg', models.FileField(upload_to='mimg/')),
            ],
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('mblno', models.IntegerField()),
                ('paddress', models.CharField(max_length=300)),
                ('pemail', models.EmailField(max_length=254)),
                ('desg', models.CharField(max_length=20)),
                ('pimg', models.FileField(upload_to='pimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('smblno', models.IntegerField()),
                ('saddress', models.CharField(max_length=300)),
                ('semail', models.EmailField(max_length=254)),
                ('simg', models.FileField(upload_to='simg/')),
            ],
        ),
    ]
