# Generated by Django 3.0.2 on 2020-03-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allimage', models.ImageField(upload_to='allimages')),
            ],
        ),
        migrations.CreateModel(
            name='Bloodimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodimage', models.ImageField(upload_to='allimages')),
            ],
        ),
        migrations.CreateModel(
            name='Foodimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodimage', models.ImageField(upload_to='allimages')),
            ],
        ),
        migrations.CreateModel(
            name='Moneyimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneyimage', models.ImageField(upload_to='allimages')),
            ],
        ),
    ]
